### PR TITLE
Change favicon

### PR DESCRIPTION
**Pull request by Iinh**
Our new chat room logo inspired me to change the app favicon too. I played around with using (2) but ended up deciding that (1) looks better. Thanks @wlach for the original design!

(1) 
gd-logo-1(4)

(2) 
gd-logo-1(5)

(1) and (2) in favicon size:

CleanShot 2021-05-26 at 10 39 04@2x

### Pull Request checklist

- [ ] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [ ] All tests and linter checks are passing
- [ ] The pull request is free of merge conflicts

### CODE REVIEW

**Review by wlach — CHANGES_REQUESTED** [review]
The icon looks a little squashed to me: 
image

A couple of things: 

1. I think the favicon should be square in dimensions
2. I actually really like the second image-- you probably just need to make a perspective transform on the G so it is also isometric.

**Comment by Iinh** [comment]
Okay here are the updated favicons. 

(1) CleanShot 2021-05-27 at 10 58 22@2x

(2) CleanShot 2021-05-27 at 11 01 00@2x



They are both square in dimension, I think the transparent png background makes them look like they're not. I like (1) because the G is not tilted so it's easier to see. 

gd-logo-1(10)

>  you probably just need to make a perspective transform on the G so it is also isometric.

I'm not sure what you mean by isometric? I aligned the G by center on Figma, but I'm not too familiar with Figma admittedly... Here's the link to view and edit the raw files: https://www.figma.com/file/TcjCI7cUGEJAoBkRBc1z73/gd-logo-1?node-id=0%3A1

gd-logo-1(8)

**Comment by wlach** [comment]
> I'm not sure what you mean by isometric? I aligned the G by center on Figma, but I'm not too familiar with Figma admittedly... Here's the link to view and edit the raw files: https://www.figma.com/file/TcjCI7cUGEJAoBkRBc1z73/gd-logo-1?node-id=0%3A1

I mean for it to look right, you need to do a perspective transformation -- i.e. you need to rotate things on the 3rd dimension. Basically the same effect we have on https://docs.telemetry.mozilla.org/favicon.svg You might need a plugin to make this work, here's one:

https://blog.visualeyes.design/10+1-Must-Have-Figma-plugins

**Comment by wlach** [comment]
Having played with the sveltekit version a bit (which I think is using the first icon), I think it looks pretty ok and I'd be happy to merge a PR which uses it. I think it might be worth trying the isometric perspective though :)

**Comment by Iinh** [comment]
Hey @wlach I tried z-rotating the G icon for (2) but I wasn't able to make it look right. I used the Isometric and Vectary 3D plugins that were recommended in the article you linked. When z-rotated 45 deg the top and bottom parts of G need to be cut to make it look natural. Here's the link to the figma again: https://www.figma.com/file/TcjCI7cUGEJAoBkRBc1z73/gd-logo-1?node-id=0%3A1

> Having played with the sveltekit version a bit (which I think is using the first icon), I think it looks pretty good and I'd be happy to merge a PR which uses it.

I like the first icon too!

**Review by wlach — APPROVED** [review]
Feel free to merge when you please! I think favicon2.png needs to be copied over favicon.png first

**Pull request merged**
