### PR TITLE
Add git last updated date in footer (fixes #495)

### LINKED ISSUE #495: Add last deploy date to footer
In #297 we added git information to the footer in the glean dictionary. It would also be nice to provide the last updated date, to give people a hint on how up to date the glean dictionary is with the information that we're getting from https://probeinfo.telemetry.mozilla.org and https://mozilla.github.io/glean-annotations/ (#494 will add nightly deploys)

Rough steps to solving this:

1. Generate a human-readable date in the rollup script (`rollup.config.js`) like "May 1st 2021"
2. Add it into the footer (`src/components/Footer.svelte`)

The end result should be a footer that says something like:

```
Last updated May 1st 2021

Alpha Software - revision 7a0a758dc3
...
```

### PR DESCRIPTION
**Pull request by chichi012**

### CODE REVIEW

**Comment by chichi012** [comment]
Hi @Iinh  I ran the tests locally, and it passed the test cases but something seems to be failing. I cant access the logs in circleci

**Comment by chichi012** [comment]
Hi @wlach, I ran the tests locally and it passed all the test cases but something seems to be failing. I can't access the logs in circleci. Any tips please?

**Comment by acmiyaguchi** [comment]
Looks like a code-linting issue:

```
> glean-dictionary@0.1.0 format:check /home/circleci/project
> prettier --plugin-search-dir=. --check .

Checking formatting...
[warn] rollup.config.js
[warn] src/components/Footer.svelte
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! glean-dictionary@0.1.0 format:check: `prettier --plugin-search-dir=. --check .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glean-dictionary@0.1.0 format:check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-08-04T00_53_50_588Z-debug.log
ERROR: "format:check" exited with 1.
npm ERR! Test failed.  See above for more details.


Exited with code exit status 1
```

**Comment by Iinh** [comment]
@acmiyaguchi could you review this PR? I'm out on sick leave and Will is on pto until next week. Thank you!

**Comment by chichi012** [comment]
Thank you for the feedback @acmiyaguchi . I've fixed the issue now

**Review by acmiyaguchi — APPROVED** [review]
This looks great, thank you.

**Pull request merged**
