### PR TITLE
Refactor package.json (fixes #317)

### LINKED ISSUE #317: Specify the dependencies in `package.json`
https://github.com/mozilla/glean-dictionary/pull/312#discussion_r555799026

We should reorganize `package.json` and specify what packages needed for production (`"dependencies"`) versus local development (`"devDependencies"`).

### PR DESCRIPTION
**Pull request by chichi012**
Merged the dependencies in "dependencies" into "devDependencies".

### CODE REVIEW

**Comment by Iinh** [comment]
Hi @chichi012 looks like some of the tests didn't pass, I think we might be having some linting issues. Please see the [Code Quality guide](https://github.com/mozilla/glean-dictionary/blob/main/docs/development.md#code-quality) to lint your code, and make sure that all tests pass locally before pushing. Let me know if you have any questions.

**Review by Iinh — CHANGES_REQUESTED** [review]
Hi @chichi012 looks like some of the tests didn't pass, I think we might be having some linting issues. Please see the [Code Quality guide](https://github.com/mozilla/glean-dictionary/blob/main/docs/development.md#code-quality) to lint your code, and make sure that all tests pass locally before pushing. Let me know if you have any questions.

**Comment by chichi012** [comment]
@Iinh I have been able to rectify the issue and I tested it locally. Thanks for the help.

**Review by Iinh — APPROVED** [review]
Looks good! Thanks @chichi012!

**Comment by chichi012** [comment]
Thank you for your help! @Iinh

**Pull request merged**
