### PR TITLE
Add BigQuery tutorial link to Help Hoverables(fixes #469)

### LINKED ISSUE #469: Provide more help on how to access BigQuery resources
This type of query doesn't work:

```sql
SELECT AVG(metrics.counter.metrics_top_sites_count)
FROM `mozdata`.org_mozilla_fenix.metrics
WHERE DATE(submission_timestamp) = '2021-01-01'
```

It seems like BigQuery gets confused when the name of a column is the same as the name of the table. For all metrics and events tables, we should prefix the column name in our BigQuery suggestion with the table name. I.e. we should suggest that people use `metrics.metrics.count.metrics_top_sites_count`.

See this slack thread for more context: https://mozilla.slack.com/archives/C4D5ZA91B/p1616015390007400

This is also relevant in the context of mozilla/data-docs#619, which I'm trying to finish up.

### PR DESCRIPTION
**Pull request by chichi012**

### CODE REVIEW

**Comment by Iinh** [comment]
This looks good, thanks @chichi012 . Let me know if you have any questions about this PR, otherwise I think this is ready to land.

**Review by Iinh — APPROVED** [review]

**Comment by Iinh** [comment]
> I was able to set up the instance of Glean Dictionary using the guide and ran the test using npm run test:jest. But I wasn't able to see the UI changes I made in my PR.

@chichi012 Since we're only adding a link to the HelpHoverable tooltip, there is effectively zero UI change. The main difference is now clicking on the tooltip directs us to the data docs, whereas we couldn't do that before.

CleanShot 2021-07-20 at 09 08 04@2x

You can compare the difference by clicking on the BigQuery tooltip in [dictionary.telemetry.mozilla.org](dictionary.telemetry.mozilla.org) (our production site) vs in [this PR Netlify deploy preview](https://deploy-preview-732--glean-dictionary-dev.netlify.app/) (or locally). 

Hope that makes sense 🙂

**Comment by chichi012** [comment]
Oh yeah it does. Thank you! @Iinh

**Comment by Iinh** [comment]
You should be able to find the BigQuery link under Access in the metric and ping page. For example, click on [this metric](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/activation_activation_id?channel=org.mozilla.firefox&ping=activation), scroll all the way down to the Access section, and you should be able to see this:

CleanShot 2021-07-21 at 19 29 57@2x

Right now we can't click on the tooltip because it's not been linked out to the docs yet, but once we merge this PR and push to production, we will be able to. You should be able to click on the tooltip locally, or you can try it in the deploy preview: https://deploy-preview-732--glean-dictionary-dev.netlify.app/apps/fenix/metrics/activation_activation_id?channel=org.mozilla.firefox&ping=activation

If this is not clear enough, I can hop on a quick call with you to walk through the code of MetricDetail and PingDetail pages :)

**Comment by chichi012** [comment]
@Iinh this was super helpful, I totally get it now. I have been been able to replicate what you showed me. Looks good to merge. Thank you.

**Comment by Iinh** [comment]
Hi @chichi012, if you could revert the last commit of updating dependencies. That is a separate issue so I think it's best that we open a separate PR for it. Once that's done I can merge this. Thanks!

**Comment by Iinh** [comment]
Congrats on your first Glean Dictionary contribution @chichi012!

**Comment by chichi012** [comment]
@Iinh thanks for flagging that. I have reverted the commit. I'll create a new PR for the package.json update

**Comment by chichi012** [comment]
@Iinh  thank you!

**Pull request merged**
