### PR TITLE
Initial attempt at using the protocol design system

### PR DESCRIPTION
**Pull request by wlach**
This is an initial attempt at styling the site using Mozilla's [protocol design system](https://protocol.mozilla.org/). It's a bit rough right now, but I think it shows potential. I like how using protocol implies a strong association with Mozilla's values, including the [lean](https://www.mozilla.org/en-US/about/policy/lean-data/) and [transparent](https://wiki.mozilla.org/Firefox/Data_Collection) data practices which are behind products like this.

image

I think for initial phases, using it alongside Tailwind makes sense-- longer term, we may want to move towards extending/using its scss framework (@craigcook recommended looking at this [gpg site](https://github.com/craigcook/gpg-static) for some inspiration)

### Work items (must be addressed before initial merge)

- [ ] Add a proper glean dictionary logo to the top-left of the site header
- [ ] Figure out appropriate heights for the various headers we're using
- [ ] Use a proper footer
- [ ] Fix the BigQuery schema viewer (some conflicts between our own styling and what's provided, it seems)

@craigcook I'd love to hear your thoughts on this, if you have any (no need to rush, I'll be on break after today).
@Iinh (and anyone else reading this) lmk if you have any thoughts too!

### Pull Request checklist

- [ ] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [ ] All tests and linter checks are passing
- [ ] The pull request is free of merge conflicts

### CODE REVIEW

**Comment by Iinh** [comment]
I really like how clean Protocol looks, and like you said @wlach, very Mozilla-like! Excited to start styling the app with Protocol, however I did notice there are limitations without using sass. Also it looks like there are conflicts between Tailwind and Protocol css reset too. 

> Work items (must be addressed before initial merge)
> - Add a proper glean dictionary logo to the top-left of the site header

1) Would the final version look similar to this @wlach (I got this from the old Glean Dictionary)

Screen Shot 2020-12-29 at 4 03 21 PM

>  - Figure out appropriate heights for the various headers we're using

2) Right now we’re using the various heading tags quite inconsistently, and [arguably incorrectly](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Usage_notes) too. I think it’d be great if we could switch to using [Protocol typography](https://protocol.mozilla.org/fundamentals/typography.html#type-scale) for better consistency, however this requires using sass. What do you think @wlach?


> - Use a proper footer
> - Fix the BigQuery schema viewer (some conflicts between our own styling and what's provided, it seems)

3 & 4. I tried addressing these 2 items with PR #299. Review appreciated :)

**Comment by wlach** [comment]
> I really like how clean Protocol looks, and like you said @wlach, very Mozilla-like! Excited to start styling the app with Protocol, however I did notice there are limitations without using sass. Also it looks like there are conflicts between Tailwind and Protocol css reset too.

We could probably skip the tailwind css reset, if we're using the protocol one: https://tailwindcss.com/docs/preflight

It is defined here: https://github.com/mozilla/glean-dictionary/blob/e0db014120bb8fccdbbc23b85b8a8c3b185af37f/src/main.css#L1

We could also consider not using tailwind altogether, and just using sass (using protocol's defaults), as I think using the combination is liable to get a bit confusing. I think it is possible to use sass inside svelte applications, similar to how we're using tailwind currently:

https://daveceddia.com/svelte-with-sass-in-vscode/

> > Work items (must be addressed before initial merge)
> > 
> > * Add a proper glean dictionary logo to the top-left of the site header
> 
>     1. Would the final version look similar to this @wlach (I got this from the old Glean Dictionary)

Something like that? 😄 It's probably worth roping in someone with an eye for design to give some suggestions (after the break)

> Screen Shot 2020-12-29 at 4 03 21 PM
> 
> > * Figure out appropriate heights for the various headers we're using
> 
>     1. Right now we’re using the various heading tags quite inconsistently. I think it’d be great if we could switch to using [Protocol typography](https://protocol.mozilla.org/fundamentals/typography.html#type-scale) for better consistency, however this requires using sass. What do you think @wlach?

I think it's a good idea, see above. 

> > * Use a proper footer
> > * Fix the BigQuery schema viewer (some conflicts between our own styling and what's provided, it seems)
> 
> 3 & 4. I tried addressing these 2 items with PR #299. Review appreciated :)

Thanks!

**Comment by Iinh** [comment]
@wlach I'm going to work on implementing sass and replace the current headers with Protocol typography.

**Comment by wlach** [comment]
> @wlach I'm going to work on implementing sass and replace the current headers with Protocol typography.

Awesome! Sounds great -- I assume by "implement SASS" you mean allowing inserting sass directives inside `<style>` blocks? I'm going to rebase this branch against `main` but will otherwise will get out of your way. 😄

**Comment by wlach** [comment]
Closing in favour of #312

**Pull request closed without merging**
