### PR TITLE
Add the missing doc links for url, rate and text

### LINKED ISSUE #1375: Links to `url` metric type Glean Book docs are broken
For a given url metric, in the Glean Dictionary, the following text is displayed at the top of the page:

> Metric of type [url](https://mozilla.github.io/glean/book/user/metrics/undefined). Sent in the [metrics](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/pings/metrics) ping.

The first link is `https://mozilla.github.io/glean/book/user/metrics/undefined` which is broken, it should be `https://mozilla.github.io/glean/book/reference/metrics/url.html#recorded-errors`

See https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/search_engine_default_submission_url

### PR DESCRIPTION
**Pull request by Dexterp37**
This slightly tweaks the check at the end to make sure that some link is present instead of a broken one.

Fixes #1375

### Pull Request checklist

- [ ] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [ ] All tests and linter checks are passing
- [ ] The pull request is free of merge conflicts

### CODE REVIEW

**Comment by Dexterp37** [comment]
@badboy any chance you could review this? This was tested by using the netlify preview, then browsing to Firefox Desktop and picking a URl metric , e.g. [here](https://deploy-preview-1381--glean-dictionary-dev.netlify.app/apps/firefox_desktop/metrics/search_engine_private_submission_url), then making sure that the doc link is correct.

**Review by badboy — APPROVED** [review]
Looks good.

**Comment by Iinh** [comment]
Thanks @Dexterp37 for catching this! I'll cut new release now to push this change to production.

**Comment by Dexterp37** [comment]
> Thanks @Dexterp37 for catching this! I'll cut a new release now to push this change to production.

Thank you so much Linh!

**Pull request merged**
